import Head from "next/head";
import styled from "styled-components";

const Hero = styled.div`
  height: 90vh;
  background: #cda6ff;
  display: flex;
  justify-content: center;
  align-items: center;
`;

const Heading = styled.h1`
  color: #fff;
  font-size: 10rem;
  font-weight: 900;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Mavnar!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Hero>
        <Heading>
          <h1>Do you Mavbar?</h1>
          <h2>Mavbar DaDeucer!</h2>
        </Heading>
      </Hero>
    </>
  );
}
